package com.freedom.dao;

import com.freedom.bean.User;
import org.springframework.stereotype.Repository;

@Repository("userMapper")
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Jun 04 23:20:02 CST 2016
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sat Jun 04 23:20:02 CST 2016
     */
    int insertSelective(User record);
}